src/main/groovy/edu/wpi/first/nativeutils/rules/JNIConfigRules.groovy

This should work on both Windows and Linux.

Use the system path.separator property to choose the path separator.

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java

This should be something enforced by GradleRIO, not native utils by default

Set the roborio compiler to be optional by default

---

build.gradle
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

In order to work properly with python, nothing with vision can be included. upstream wpilibc no longer includes a reference to opencv or vision

Bypass vision libraries with the default wpilib configurations

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/OrderedStripTask.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
build.gradle
src/main/java/edu/wpi/first/nativeutils/configs/PrivateExportsConfig.java
src/main/java/edu/wpi/first/nativeutils/configs/impl/DefaultPrivateExportsConfig.java
src/main/java/edu/wpi/first/nativeutils/rules/PrivateExportsConfigRules.java

This will run "--strip-all --discard-all" on private symbol binaries with the flag set. Reduces footprint of libraries.

Enable support for fully stripping shared binaries with private symbols

---

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

They will still be extracted for runtime purposes

Skip directly linking to JNI libraries

---

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

On AppleClang 12 (with macOS 11.0), including WPILib-OpenCV headers causes the build to fail. Example scan here: https://gradle.com/s/4bndkaxghnipk
This flag also works on macOS 10.15 Catalina. CI build for that here: https://github.com/prateekma/allwpilib/runs/1027361880?check_suite_focus=true

Add -Wno-error=c11-extensions to macOS compiler

---

build.gradle
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

Get a bunch of unresolved symbols without it.
```
/Users/prateekma/.gradle/caches/transforms-2/files-2.1/70f0edbb526dd8c20db42fc076c65de1/wpimath-cpp-2021.3.1-linuxathenastaticdebug/linux/athena/static/libwpimathd.a(Rotation2d.o): In function `wpi::detail::json_ref<wpi::json>::json_ref(std::initializer_list<wpi::detail::json_ref<wpi::json> >)':
/__w/allwpilib/allwpilib/wpiutil/src/main/native/include/wpi/json.h:2284: undefined reference to `wpi::json::json(std::initializer_list<wpi::detail::json_ref<wpi::json> >, bool, wpi::detail::value_t)'
/Users/prateekma/.gradle/caches/transforms-2/files-2.1/70f0edbb526dd8c20db42fc076c65de1/wpimath-cpp-2021.3.1-linuxathenastaticdebug/linux/athena/static/libwpimathd.a(Rotation2d.o): In function `wpi::json::~json()': …
```

Fix static link order

---

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

For wpilibsuite/allwpilib#3297

Allow C enums with fixed underlying type on macOS

---

src/main/java/edu/wpi/first/nativeutils/sourcelink/SourceLinkGenerationTask.java

Closes #60 
Since SSH is rarely used on windows, and sourcelink is only useful for publishing, its not needed locally, and we can just skip it upon failure.

Skip sourcelink when cloned with SSH

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java

Its possible there are teams with school computers that cannot install a custom JDK. If theyre running M1 macs, it is impossible for them to build robot code, as x86 artifacts will get looked for for configuring sim. Using any non aarch64 binaries will fail to run, but we do need builds to at least compile. So make arm64 jdks show up as x64 rather then x86, so at least binaries will always exist.

Treat arm64 arch as x64

---

README.md
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32Gcc.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainPlugin.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64Gcc.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainPlugin.java
ToolchainPlugin/src/test/groovy/edu/wpi/first/toolchain/arm32/Arm32DownloadTest.groovy
ToolchainPlugin/src/test/groovy/edu/wpi/first/toolchain/arm64/Arm64DownloadTest.groovy
ToolchainPlugin/src/test/groovy/edu/wpi/first/toolchain/roborio/RoborioDownloadTest.groovy
build.gradle
src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

Also, because arm has gotten a bit better, rename raspbian to arm32 and bionic to arm64. We probably should also investigate moving the bionic compiler to arm64 raspberry pi builds.

Support building natively on arm32 and arm64

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
build.gradle

On intel mac systems, when doing a dual build, we can't run the arm64 tests. Modify the existing code that disables cross compiled tests to work for any non native build. This would cause win32 tests to not be able to be ran, however since we've removed win32 that is no longer a concern. We can always special case any builds in the future that would work. Technically we could allow m1 macs to run intel tests, but probably not worth doing so.
Uses a pre initialized interface both to reduce allocations, and ensure we don't break incremental builds.
Tested on mac to know it works.

Disable all run test tasks except for the native build

---

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

clang-tidy says it's unused for object file compilations:
```
== clang-tidy /__w/allwpilib/allwpilib/wpinet/src/test/native/cpp/WebSocketTest.h ==
error: argument unused during compilation: '-rdynamic' [clang-diagnostic-unused-command-line-argument]
```
See also https://stackoverflow.com/a/64449275.

Remove -rdynamic compiler argument

---

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
src/main/java/edu/wpi/first/nativeutils/exports/ExportsConfig.java
src/main/java/edu/wpi/first/nativeutils/exports/ExportsGenerationTask.java

But make it not added to the 64 bit build, so it requires a 32 bit jdk.
I ran format on the WPINativeUtilsExtension file, which is why theres a lot of changes. But its basically bringing back everything that was in 32 bit, except for the cross build capabilities.

Add windows 32 bit build back to native utils

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/DefaultToolchainInstaller.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainPlugin.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainPlugin.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java
build.gradle

This makes it so an arm cross compiler will be used even with an intel jdk. Because the call can be expensive, lazily compute the hw arch only when necessary.

Use mac hw platform for compiler arch

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDiscoverer.java
build.gradle

The option conversion wouldn't accept a null, but a compiler that can't be ran would result in a null metadata component.
Closes #43

Fix native utils crashing when a non runnable compiler is found

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/GccToolChain.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDiscoverer.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainPlugin.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRootExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainPlugin.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainPlugin.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainBase.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java
build.gradle

This allows us to get rid of the buildFinished listener, which is deprecated.

Move static variables to a root extension

---

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

Since we don't include the static apriltaglib library, it won't work anyway. If someone needs it, we can provide the method to manually add those 2 dependencies to a project

Remove support for static apriltag library

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
build.gradle

Gradle expects to call gcc with -x assembler rather then as directly

Fix cross compilers being able to use assembly

---

build.gradle
src/main/java/edu/wpi/first/nativeutils/vendordeps/ConflictingVendorDependencyException.java
src/main/java/edu/wpi/first/nativeutils/vendordeps/MissingRequiredVendorDependencyException.java
src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java
testing/cpp/build.gradle

One of the biggest requests for vendor deps has been handling transitive dependencies. Doing this properly is a hard problem. @JCaporuscio had a suggestion for building a basic setup, to allow enabling this for many of the cases without causing a massive amount of development pain.
The basic idea of this is each dependency can have a `requires` and a `conflictsWith` block. Each of these blocks contains an array of objects, each containing 3 elements.
uuid: The uuid that is required or that is conflicting
errorMessage: An error message to be displayed to the user
onlineUrl: The url to search for this vendor dep during installation (This isn't used by this PR, but will be used for the dep loader)
Once all dependencies have been loaded, the entire dep tree is searched. If a dependency has a …

Add a basic vendor deps dependency mechanism

---

src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java

We want to add a check for this, but I want that check to be in GradleRIO for configuration reasons. Add just to the schema.

Add frcYear to vendor dep schema

---

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java

Theres an override if someone wants this behavior back.

Remove GCC and Clang toolchains from being found by default on windows

---

build.gradle
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
testing/cpp/build.gradle

macOS 12 is EOL in mid-October of 2024 based on when macOS 11 was dropped last year.

Bump macOS deployment target to 13

---

build.gradle
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
testing/cpp/build.gradle

DependentLoadFlags is something added in Windows 10 RS1 that allows modules to specify how they load their dll dependencies. By default, the application path, system32, and some other paths are searched. However, for our use this is kind of a pain, as when we extract libraries, they're not in the same path as the executable.
This PR adds the LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR flag, which lets us specify to load from our own dll directory first.

Set DependentLoadFlags on windows binaries

---

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

It's finally time we fix all of our rpath issues, especially on macOS.
Force RPATH to $ORIGIN always on Linux. Force RPATH to @loader_path always on macOS. An upcoming PR will make the loader_path thing work on macOS properly.

Force RPATH to ORIGIN or loader_path

---

build.gradle
src/main/java/edu/wpi/first/nativeutils/RpathRules.java
src/main/java/edu/wpi/first/nativeutils/WPINativeUtils.java
testing/cpp/build.gradle

On macOS, in order to pick up rpath properly for downstream dependencies, the install name must be prefixed with rpath. Do that, so dependent libraries will be properly picked up.

Set rpath on install_name on macOS

---

README.md
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java

Closes #210 
Do not merge until we are ready to update gradlerio to 2025. This will break gradlerio. This will also break any vendors not pointing to newer wpilib artifacts.

Switch googletest to use artifacts from monorepo

---

src/main/java/edu/wpi/first/nativeutils/vendordeps/VendorParsingError.java
src/main/java/edu/wpi/first/nativeutils/vendordeps/VendorParsingException.java
src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java

Resolves [GradleRIO#727](https://github.com/wpilibsuite/GradleRIO/issues/727)
This reports errors when the vendor file is missing required keys. Instead of throwing a build exception directly we throw a custom exception that will be consumed by the BuildException when we call load.

[vendordeps] handle null keys better

---

.gitignore
build.gradle
src/main/java/edu/wpi/first/nativeutils/vendordeps/VendorDepTask.java
testing/cpp/build.gradle

Resolves https://github.com/wpilibsuite/native-utils/issues/196
Also makes testing project use vendordeps plugin

[vendordeps] Use fileName in download

---

.github/workflows/main.yml
README.md
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/FrcHome.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/systemcore/SystemCoreToolchainExtension.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/systemcore/SystemCoreToolchainPlugin.java
ToolchainPlugin/src/test/groovy/edu/wpi/first/toolchain/systemcore/SystemCoreDownloadTest.groovy
build.gradle
src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
testing/cpp/build.gradle

Right now just use the bookworm compiler.
Also updates to the 2025 compilers.

Add SystemCore to supported platforms

---

src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java

Does not parse hidden files. Fixes wpilibsuite/GradleRIO#726 
Identifies file that failed to load or parse

Improve vendor dep error handling for malformed files

---

build.gradle
src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
testing/cpp/build.gradle

We now only support GCC 11+, so we can remove the conditional flag inclusion.

Suppress enum-enum conversion warning on Linux cross compilers

---

README.md
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java
ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java
build.gradle
src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java
testing/cpp/build.gradle

This fixes NativeUtilsExtension by explicitly adding "fakeplatform" to the list of platforms to configure if the project sees a `-Ponly*` flag, provided "fakeplatform" hasn't already been added to the list.
This also updates the README to describe the purpose of fakeplatform and how to enable it.
This has been tested both with and without `-Ponly*` flags for native and linuxathena, and with and without `-Pusefakeplatform`, on Windows and Linux x86-64.

Fix fakeplatform being stripped by -Ponly*, and update README
