wpilibsuite/native-utils

ToolchainPlugin/build.gradle, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/AbstractToolchainInstaller.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/DefaultToolchainInstaller.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/GccToolChain.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/InstallToolchainTask.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDescriptor.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDiscoverer.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainOptions.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRegistrar.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/raspbian/RaspbianGcc.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/raspbian/RaspbianToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/raspbian/RaspbianToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/FrcHome.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioGcc.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java, build.gradle, settings.gradle
Moved from GradleRIO to here.
Here, its more easily usable from both WPILib and Vendor Libraries
=> Add Toolchan Plugin

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/configurable/ConfigurableGcc.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/configurable/CrossCompilerConfiguration.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/configurable/DefaultCrossCompilerConfiguration.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/raspbian/RaspbianToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java
Uses a DSL to be configurable from a build script, along with easier support for our toolchains
=> Add support for easily configurable toolchains

src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java
=> Only skip x86 on windows 64 bit

ToolchainPlugin/build.gradle, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/GccToolChain.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDescriptor.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDescriptorBase.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/bionic/BionicToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/configurable/CrossCompilerConfiguration.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/configurable/DefaultCrossCompilerConfiguration.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/raspbian/RaspbianToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/xenial/XenialToolchainPlugin.java, build.gradle, src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java
The optional had ordering issues otherwise, and the single print is needed otherwise 400 lines of warnings happen per build.
Depends on https://github.com/JacisNonsense/EmbeddedTools/pull/53
=> Update Optional to use a property, add single missing TC support

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
Includes all libraries safe to use from a JNI library
=> Add jni combined configuration

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java, src/main/java/edu/wpi/first/nativeutils/rules/DependencyConfigRules.java
To solve exe rpath linking errors, and making libraries depend on less NI libraries
=> Add a separate ni_runtime dependency

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
=> Enable /bigobj for C++ on windows

build.gradle, src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java
=> Fix getPublishClassifier() arg type

build.gradle, src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java, src/main/java/edu/wpi/first/nativeutils/rules/DependencyConfigRules.java
The PDB's take up a lot of space, and CI is running out of room
=> Add way to skip installing PDB's for install tasks

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java
The 2022 compiler has a 64-bit windows version.
=> Update for 2022

build.gradle, src/main/java/edu/wpi/first/nativeutils/NativeUtils.java, src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java, src/main/java/edu/wpi/first/nativeutils/dependencies/AllPlatformsCombinedNativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/ArtifactType.java, src/main/java/edu/wpi/first/nativeutils/dependencies/CombinedIgnoreMissingPlatformNativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/CombinedNativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/DelegatedDependencySet.java, src/main/java/edu/wpi/first/nativeutils/dependencies/FastDownloadDependencySet.java, src/main/java/edu/wpi/first/nativeutils/dependencies/NativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPISharedMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIStaticMavenDependency.java
=> Add method to download native dependencies faster

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDescriptor.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/bionic/BionicToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/raspbian/RaspbianToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java
Supersedes #88 
Thanks @Namos0613
=> Use ObjectFactory to create toolchain object sets

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDescriptor.java, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java, src/main/java/edu/wpi/first/nativeutils/dependencies/CustomDependencySet.java, src/main/java/edu/wpi/first/nativeutils/dependencies/DelegatedDependencySet.java, src/main/java/edu/wpi/first/nativeutils/dependencies/FastDownloadDependencySet.java, src/main/java/edu/wpi/first/nativeutils/resources/ResourceGenerationAction.java, src/main/java/edu/wpi/first/nativeutils/resources/ResourceGenerationTask.java, src/main/java/edu/wpi/first/nativeutils/resources/ResourceWorkParameters.java
Custom dep sets are useful for users. Resource generation is used by multiple wpilib projects, and is better to have standardized
=> Add resource generation and custom dep set helpers

build.gradle, src/main/java/edu/wpi/first/nativeutils/resources/ResourceGenerationAction.java
=> Fix extra semi colon in resource gen task

build.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
=> Switch fully to 2023 maven artifacts

build.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIVendorMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/vendordeps/VendorDepTask.java, src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIJavaVendorDepsExtension.java, src/main/java/edu/wpi/first/nativeutils/vendordeps/WPINativeVendorDepsExtension.java, src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java, src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsPlugin.java
This has been requested by a few groups. Its pretty easy to do
=> Move vendor deps to native utils

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDescriptor.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainBase.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java, ToolchainPlugin/src/test/groovy/edu/wpi/first/toolchain/arm32/Arm32DownloadTest.groovy, ToolchainPlugin/src/test/groovy/edu/wpi/first/toolchain/arm64/Arm64DownloadTest.groovy, ToolchainPlugin/src/test/groovy/edu/wpi/first/toolchain/roborio/RoborioDownloadTest.groovy, build.gradle
There was a lot of copy pasted code.
=> Add an opensdk base for all the toolchains to share code

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/NativePlatforms.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainBase.java, build.gradle
Tested on WSL2 on an Arm dev box
=> Add option to install arm host cross toolchains

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/GccExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainDiscoverer.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainExtension.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainGraphBuildService.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/ToolchainRules.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm32/Arm32ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/arm64/Arm64ToolchainPlugin.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainBase.java, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/roborio/RoboRioToolchainPlugin.java
Also fixes a bug where the skip optional property was not checked
=> Switch root extension to build service

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainExtension.java
Needed to pick up new signed binaries.
=> Update to v6 toolchain release

README.md, ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainExtension.java, build.gradle, settings.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java, src/main/java/edu/wpi/first/nativeutils/sourcelink/SourceLinkGenerationTask.java, testing/cpp/settings.gradle
Also removes imgui, as it can be grabbed manually. And also forces the wpimath version to match wpilib, as I don't expect that will be split back out.
=> Add apriltag into native-utils

build.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
This reverts commit 3a1635c835c694aa22ecd146017d60a53012bb53.
=> Revert "Use correct apriltags name... (#144)"

src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java
=> Fix frcYear string

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/opensdk/OpenSdkToolchainBase.java, build.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
=> Fix arm cross compilers, easy way to add gcc 11 args, macos minimum version

build.gradle, src/main/java/edu/wpi/first/nativeutils/dependencies/MissingVendorDependencyPlatformException.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIVendorMavenDependency.java, testing/cpp/build.gradle
=> Fix error when vendor dep requires a platform that doesn't exist

src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java
We are able to configure this a lot easier if we move it into GradleRIO.
=> Remove automatic load all for vendor deps

build.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java, testing/cpp/build.gradle
There are false positives in this case.
=> Disable Werror=deprecated-declarations on GCC 10

build.gradle, src/main/java/edu/wpi/first/nativeutils/NativeUtilsExtension.java, src/main/java/edu/wpi/first/nativeutils/dependencies/AllPlatformsCombinedNativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/CombinedIgnoreMissingPlatformNativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/CombinedNativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/DelegatedDependencySet.java, src/main/java/edu/wpi/first/nativeutils/dependencies/NativeDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIHeaderOnlyMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPISharedMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIStaticMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/dependencies/WPIVendorMavenDependency.java, src/main/java/edu/wpi/first/nativeutils/platforms/PlatformRules.java, testing/cpp/build.gradle
Grapple needs this to be able to hook into their rust libraries easier. Also much cleaner and easier to use
=> Add a method to manually grab native dependencies

build.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java, testing/cpp/build.gradle
See [discord](https://discord.com/channels/176186766946992128/368993897495527424/1236351086898450513)
=> Bump macOS deployment target to 13.3

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
Was added to allwpilib, should be put everywhere.
=> Add Wno-deprecated-anon-enum-enum-conversion to macOS

build.gradle, src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java, testing/cpp/build.gradle
See https://github.com/wpilibsuite/allwpilib/pull/7028/
=> Add 4324 to ignored warnings

build.gradle, src/main/java/edu/wpi/first/nativeutils/vendordeps/VendorDepTask.java, testing/cpp/build.gradle
Resolves https://github.com/wpilibsuite/GradleRIO/issues/746
Requires https://github.com/wpilibsuite/native-utils/pull/217
=> [vendordeps] Add an option to update vendordeps

ToolchainPlugin/src/main/java/edu/wpi/first/toolchain/systemcore/SystemCoreToolchainPlugin.java, build.gradle, testing/cpp/build.gradle
The toolchain was told its targeting the wrong target.
=> Fix incorrect systemcore platform

build.gradle, src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIJavaVendorDepsExtension.java, src/main/java/edu/wpi/first/nativeutils/vendordeps/WPINativeVendorDepsExtension.java, src/main/java/edu/wpi/first/nativeutils/vendordeps/WPIVendorDepsExtension.java, testing/cpp/build.gradle
Needed for vendor deps with hwsim to work properly.
=> Treat systemcore as a roborio like platform

src/main/java/edu/wpi/first/nativeutils/WPINativeUtilsExtension.java
Until we get an updated compiler, we need this to determine if we have a systemcore build or not.
=> Add a custom systemcore define
